# general aliases
alias ll='ls -la'
alias mk='mkdir'
alias rd='rm -r'
alias vrc='vim -p ~/.profile ~/.bashrc ~/.bash_profile'
alias .rc='. ~/.bash_profile'
alias cpr='cp -R'
alias o='open .'
alias tch='touch'
alias src='source'
alias supi='sudo pico'
alias gitit='git init'
alias gitone='git clone'
alias gitadd='git add'
alias gitadda='git add -A'
alias gitdel='git add . -A'
alias gitcom='git commit -m'
alias gitrem='git remote add origin'
alias gitremrm='git remote rm origin'
alias gitpush='git push origin master'
alias gitstat='git status'
alias delfil='rm -Rf'
alias home='cd ~/'
alias rt='cd /'

# folder aliases
alias hlmel='cd ~/Hello-Mel && ll'
alias dev='cd ~/dev && ll'# general aliases
alias ll='ls -la'
alias mk='mkdir'
alias rd='rm -r'
alias vrc='vim -p ~/.profile ~/.bashrc ~/.bash_profile'
alias .rc='. ~/.bash_profile'
alias o='open .'
alias tch='touch'
alias src='source'
alias supi='sudo pico'
alias gitit='git init'
alias gitone='git clone'
alias gitadd='git add'
alias gitadda='git add -A'
alias gitdel='git add . -A'
alias gitcom='git commit -m'
alias gitrem='git remote add origin'
alias gitremrm='git remote rm origin'
alias gitpush='git push origin master'
alias delfil='rm -Rf'
alias home='cd ~/'
alias rt='cd /'

# folder aliases
alias hlmel='cd ~/Hello-Mel && ll'
alias dev='cd ~/dev && ll'
